package app.myphonecheck.mobile.feature.decisionui.components

import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import app.myphonecheck.mobile.feature.decisionui.theme.MyPhoneCheckTheme

/**
 * Displays up to 3 supporting reasons for the decision.
 * Reasons come directly from DecisionResult.reasons (generated by SummaryGenerator).
 */
@Composable
fun ReasonsList(
    reasons: List<String>,
    modifier: Modifier = Modifier,
) {
    Column(modifier = modifier) {
        reasons.take(3).forEach { reason ->
            ReasonItem(reason = reason)
        }
    }
}

@Preview(showBackground = true)
@Composable
private fun ReasonsListPreview() {
    MyPhoneCheckTheme {
        ReasonsList(
            reasons = listOf(
                "발신 3회, 수신 5회, 평균통화 120초",
                "검색 결과: 택배/배송 관련 키워드 발견",
                "최근 2일 내 통화 이력",
            ),
        )
    }
}

@Preview(showBackground = true)
@Composable
private fun ReasonsListScamPreview() {
    MyPhoneCheckTheme {
        ReasonsList(
            reasons = listOf(
                "저장되지 않은 번호, 기기 기록 없음",
                "검색 결과: 사기/피싱 관련 키워드 다수",
            ),
        )
    }
}
